name: SmsServerUtils
version: @version@
main: uwu.smsgamer.smsserverutils.Loader
softdepend: [ ProtocolLib, PlaceholderAPI ]
authors: [ Sms_Gamer_3808 ]
description: A ton of utilities for server operators.
commands:
  evaluate:
    description: Evaluates a query based off of user input.
    usage: /eval <python command>
    aliases:
      - eval
